# Generated by Django 3.1.6 on 2021-02-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=20)),
                ('team_type', models.CharField(max_length=20)),
                ('comment', models.TextField()),
                ('dev_category', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=10)),
            ],
        ),
    ]
